# Anyone with write permissions to the antrea-io/antrea-image-utis Github
# repository can trigger this workflow manually, but please check with a
# maintainer first.
name: Update antoninbas/antrea-lichen Docker image

on:
  workflow_dispatch:
    inputs:
      go-version:
        description: 'The Go version to use to build and run lichen'
        required: false
        default: '' # there is a default version in the Dockerfile
      lichen-version:
        description: 'The lichen version to install'
        required: false
        default: '' # there is a default version in the Dockerfile
      docker-tag:
        description: 'Tag for built Docker image'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set docker build args
      run: |
        args="[]"
        if [ "${{ github.event.inputs.go-version }}" != "" ]; then
          args=$(echo "$args" | jq '. += ["GO_VERSION=${{ github.event.inputs.go-version }}"]')
        fi
        if [ "${{ github.event.inputs.lichen-version }}" != "" ]; then
          args=$(echo "$args" | jq '. += ["LICHEN_VERSION=${{ github.event.inputs.lichen-version }}"]')
        fi
        echo "docker_build_args=${args}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: images/lichen
        platforms: linux/amd64 # no need for other platforms
        build-args: ${{ fromJSON(env.docker_build_args) }}
        push: true
        tags: antoninbas/antrea-lichen:${{ github.event.inputs.docker-tag }}
        no-cache: true
