name: Build and push antoninbas/antrea-test-2 Docker image

on:
  pull_request:
    branches:
      - main
    paths:
      - 'images/test-2/**'
  push:
    branches:
      - main
    paths:
      - 'images/test-2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set docker tag
      working-directory: images/test-2
      run: |
        version=$(head -n 1 VERSION)
        version_update_sha=$(git log -n 1 --pretty=format:%H -- VERSION)
        rev=$(git rev-list --count ${version_update_sha}..HEAD -- .)
        echo "version=${version}" >> $GITHUB_ENV
        echo "rev=${rev}" >> $GITHUB_ENV
        echo "docker_tag=${version}-${rev}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      if: ${{ github.repository == 'antoninbas/antrea-image-utils' && github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: images/test-2
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: ${{ github.repository == 'antoninbas/antrea-image-utils' && github.event_name != 'pull_request' }}
        # first tag should be immutable, others are rolling tags
        tags: antoninbas/antrea-test-2:${{ env.docker_tag }},antoninbas/antrea-test-2:${{ env.version }},antoninbas/antrea-test-2:latest
        no-cache: true
